/*
 * This source file was generated by the Gradle 'init' task
 */
package megalomaniak;

import org.megalomaniak.Megalomaniak;
import org.megalomaniak.MegalomaniakClient;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestInstance.Lifecycle;

import static org.junit.jupiter.api.Assertions.*;

@TestInstance(Lifecycle.PER_CLASS)
class AppTest {

    private MegalomaniakClient client;

    @BeforeAll
    public void setup() {
        client = Megalomaniak.createClient();
    }

    @Test
    void callExistingEndpoint() {
        // client.CallEndpoint("/api/players", null);
    }
}
