/*
 * This source file was generated by the Gradle 'init' task
 */
package megalomaniak;

import org.mikkosdev.megalomaniak.Megalomaniak;
import org.mikkosdev.megalomaniak.MegalomaniakServer;
import org.mikkosdev.megalomaniak.core.AbstractNode;

public class App {
    public static void main(String[] args) throws InterruptedException {
        System.out.println("Starting Megalomaniak server...");

        AbstractNode node = new MyNode();
        MegalomaniakServer server = Megalomaniak.createServer(8080, 8088, node);
        server.setNode(node);   // This is not necessary, but here for completeness
        server.start();
    }
}
